from src.common.constants.application_constants import WINDOW_HEIGHT

OFFSET = 50
CHAT_WIDTH = 400
CHAT_INPUT_HEIGHT = 50
CHAT_OUTPUT_HEIGHT = 300
CHAT_INPUT_RECT = (50, WINDOW_HEIGHT - CHAT_INPUT_HEIGHT - OFFSET, CHAT_WIDTH, CHAT_INPUT_HEIGHT)
CHAT_OUTPUT_RECT = (OFFSET, WINDOW_HEIGHT - CHAT_INPUT_HEIGHT - CHAT_OUTPUT_HEIGHT - OFFSET, CHAT_WIDTH, CHAT_OUTPUT_HEIGHT)
